/// Flutter icons Inventory
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Inventory
///      fonts:
///       - asset: fonts/Inventory.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Inventory {
  Inventory._();

  static const _kFontFam = 'Inventory';
  static const String? _kFontPkg = null;

  static const IconData healthpotion = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData manapotion = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twelvegods = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData proviant = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData schmerz = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mana = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
